### ISSUE TITLE
请问下 字体比较模糊应该怎么处理?激活控件就会很清晰 感谢

### ISSUE THREAD

**Issue by eqk215** [rhett-lee/nim_duilib#16]
![动画111](https://github.com/rhett-lee/nim_duilib/assets/166944281/a6e57a17-114b-4629-92fd-2b7f76717790)

**Comment by rhett-lee** [comment]
这个问题看起来似乎和DPI缩放有关系，模糊现象，感觉是被操作系统拉伸放大的。
需要和您提供一下信息：出现模糊的操作系统是什么版本？桌面的DPI是多少？
我在Win7 x64系统（DPI缩放200%）/Win11 x64（DPI缩放200%）系统验证，都没发现字体模糊问题。
所以希望提供一下环境信息，我再利用以上信息再验证一下。

**Comment by eqk215** [comment]
当前系统版本 Win10 1909  DPI 100%  刚测试了下 改为200%很清晰 但太大了    有办法解决吗  感谢

**Comment by rhett-lee** [comment]
按照你给的环境，这个问题我重现出来了。字体在DPI为100%的情况下，确实存在模糊现象。
我测试了很多方法，但是没有解决，预计解决这个问题有些复杂。
所以，这个问题的解决方法，我需要再研究一下，等有了进展再回复。

**Comment by eqk215** [comment]
好的感谢

**Comment by rhett-lee** [comment]
这个问题已经修复了。请更新一下最新的代码试试看吧。

**Comment by eqk215** [comment]
测试了下  很清晰  编译出来的exe 比较大

**Comment by rhett-lee** [comment]
Debug版本的exe体积比较大，但Release版本的exe体积还不算太大。使用Skia引擎后，由于引入的代码量比较多，体积会增加很多的。
