### ISSUE TITLE
Menu内绑定鼠标单击处理函数 调用fileDlg.BrowseForFile 或GetOpenFileName 连续两次或三次就会触发异常 不知道是我没写对还是什么原因

### ISSUE THREAD

**Issue by eqk215** [rhett-lee/nim_duilib#19]
## 问题现象

![93e63c42-8962-4f7d-8c8e-2e6de9663e13](https://github.com/rhett-lee/nim_duilib/assets/166944281/570ddd2d-312c-45ed-98d7-6542c44faaad)
![QQ截图20240611045836](https://github.com/rhett-lee/nim_duilib/assets/166944281/8cce1b5c-891c-4043-a5d5-de903d039aff)

**Comment by rhett-lee** [comment]
问题重现出来了，原因是在菜单命令中显示了选择文件的对话框导致的，这种情况下存在Bug。我看看怎么修正这个问题，解决后再回复。

**Comment by rhett-lee** [comment]
问题已经修正了，请更新一下最新的代码试试看吧。消息接口有修改：EventArgs.pSender 变量改为使用函数了：EventArgs.GetSender()，如有使用，代码也需要调整一下。

**Comment by eqk215** [comment]
测试没问题了
