### ISSUE TITLE
Use the release version of skia to improve rendering efficiency in duilib debug mode

### ISSUE THREAD

**Issue by mandomwu** [rhett-lee/nim_duilib#27]
**1. Compile the debug version of skia like the release version (add extra_cflags=[\"/MTd\"] at the end)**
` .\bin\gn.exe gen out/LLVM.x86.Debug --ide='vs2019' --sln='skia' --args='target_cpu=\"x86\" cc=\"clang\" cxx=\"clang++\" clang_win=\"C:/LLVM\" clang_win_version=\"18\" is_trivial_abi=false is_official_build=true skia_use_system_libpng=false skia_use_system_libjpeg_turbo=false skia_use_system_zlib=false skia_use_icu=false skia_use_expat=false skia_use_libwebp_decode=false skia_use_libwebp_encode=false skia_use_xps=false skia_enable_pdf=false is_debug=false extra_cflags=[\"/MTd\"]'`

**2.In the settings of the duilib project, add the predefined macro "SK_RELEASE"**
```
   Original definition "WIN32;_DEBUG;_WINDOWS;SK_GANESH;SK_GL"
   Added definition: "WIN32;_DEBUG;_WINDOWS;SK_GANESH;SK_GL;SK_RELEASE;"  
```

**3.Remove GR TEST_UTILS detection in duilib project sourcecode**
```
  #ifdef _DEBUG
    #ifdef GR_TEST_UTILS
        #error 请检查宏定义：GR_TEST_UTILS与Skia库的编译选项保持一致（DisplayParams/GrContextOptions）
    #endif
#else
    #ifdef GR_TEST_UTILS
        #error 请检查宏定义：GR_TEST_UTILS与Skia库的编译选项保持一致（DisplayParams/GrContextOptions）
    #endif
#endif
```
 tip:There is this macro definition in two files

**Comment by rhett-lee** [comment]
这个方法不错，能够提高Debug版本的绘制速度，能够提高调试的效率。代码已经修改并提交了，更新代码后，需要按照skia_compile库中最新的方法，重新编译以下Skia库。
