### ISSUE TITLE
When using the colorpicker to pick a color from the screen, the program crashes

### ISSUE THREAD

**Issue by mandomwu** [rhett-lee/nim_duilib#28]
**1.Problem Description**
When running controls.exe, the colorpicker window opens; the program crashes。
The vs2019 debug output window displays the following error message
```
HEAP CORRUPTION DETECTED: after Normal block (#706823) at 0x08A84EB0.
CRT detected that the application wrote to memory after end of heap buffer.
```
![crash](https://github.com/user-attachments/assets/c6c2bfd7-252f-4bba-99a5-c1a69080c926)

**2.Cause of the bug**
In the GetMousePosBitmap function of the ColorPicker.cpp file, 
`pDestPixelBits[++destColorIndex] = pPixelBits[colorXY]; `
the access subscript of ++destColorIndex starts at 1, so pDestPixelBits will be written out of bounds; it crashes when released; the problem is solved after changing to
``pDestPixelBits[destColorIndex++] = pPixelBits[colorXY]; ``

**Comment by rhett-lee** [comment]
这个缺陷已经修复。
