### ISSUE TITLE
SDL版本是否考虑支持SDL的渲染，而非skia混合使用

### ISSUE THREAD

**Issue by wangqiangcc** [rhett-lee/nim_duilib#40]
SDL版本是否考虑支持SDL的渲染，而非skia混合使用, 优点是整体编译时间、程序体积会小一点

**Comment by rhett-lee** [comment]
短期内不考虑支持SDL的渲染，主要原因：
1. SDL版本目前的开发仅完成了Windows版本，一些想支持的Linux系统还没有完成适配，所以当前的主要开发精力会集中放在SDL的开发完善方面，预计还需要一段时间，SDL3本身也还没有正式的发布Release版本，期间还会不断对SDL3进行适配完善；
2. nim_duilib本身还有不少需要完善的地方，这些会作为现阶段的重点；
3. SDL的渲染接口在功能方面，仅提供了基础的功能，很多绘制功能都需要自己编码实现，所以要想替换现有的Skia渲染引擎，开发工作量很大，并且需要舍弃一部分基于SDL渲染引擎无法实现的功能。所以暂时不会考虑支持SDL的渲染。

**Comment by wangqiangcc** [comment]
SDL2有一个gfx的渲染库可以使用https://sourceforge.net/projects/sdlgfx/
可以兼容SDL3 https://github.com/wangqiangcc/SDL3_gfx/blob/master/SDL3_compat.h 
后期希望能考虑一下

**Comment by rhett-lee** [comment]
收到，感谢提供支持。
目前Windows平台使用Skia + Windows SDK实现，使用LLVM + Visual Studio编译的环境下，基本功能算是比较完善了，应该能够较好的满足Windows平台应用程序的界面库之用。
但是，在使用Skia + SDL3实现，使用LLVM + Visual Studio在Windows平台环境下，基本功能刚刚开发完成，基础测试可用性还可以；在使用LLVM + gcc/g++在Linux平台环境下，目前刚刚开始适配，还有不少工作要做。总体上，还是想先把Skia + SDL3实现在Windows平台/Linux平台下的功能做完善，可用性方面做到位，然后再考虑优化渲染库。你说的方案挺好的，如果不依赖Skia的情况下，能够做到较好的界面呈现效果，依赖更少，维护和扩展方面也就更加容易了。我先记下来了，等时机成熟的时候，我再调研看看。
