### ISSUE TITLE
关于已知问题 nim_duilib 双击标题栏时，不能够最大化/还原操作

### ISSUE THREAD

**Issue by wangqiangcc** [rhett-lee/nim_duilib#43]
你好，我在看到 跨平台开发相关事项 已知问题 nim_duilib 双击标题栏时，不能够最大化/还原操作, 我记得是SDL3上面的问题，在SDL2上面是没有问题的 可以参考 https://github.com/wangqiangcc/SDL_gui  这个示例 SDL_gui\tests\0100_GUI_App\_VisualC\WinApp 希望能给你提供一些帮助。

**Comment by rhett-lee** [comment]
收到，谢谢，我先看一下，这个问题是仅在Linux平台有问题，在Windows平台下是正常的。
